// Allow dead code for work-in-progress modules and registry systems
#![allow(dead_code)]

mod file_ops;
mod git_ops;
mod app;
mod extension_ops;
mod monitoring;
mod terminal_ops;
mod window_ops;
mod debug_ops;
mod search_ops;
mod session_ops;
mod command_registry;
mod command_ops;
mod menu_registry;
mod menu_ops;
mod extension_menu_parser;
mod keybinding_registry;
mod keybinding_ops;
mod extension_keybinding_parser;
mod status_bar_registry;
mod status_bar_ops;
mod activity_bar_registry;
mod activity_bar_ops;
mod language_features_registry;
mod language_features_ops;
mod workspace_registry;
mod workspace_ops;
mod filesystem_registry;
mod filesystem_ops;
mod textdocument_registry;
mod textdocument_ops;
mod configuration_registry;
mod configuration_ops;
mod debug_configuration_registry;
mod debug_configuration_ops;
mod theme_registry;
mod theme_ops;
mod task_registry;
mod task_ops;
mod settings_ui_registry;
mod settings_ui_ops;
mod marketplace_ui_registry;
mod marketplace_ui_ops;
mod test_runner_registry;
mod test_runner_ops;
mod secrets_ops;

pub use file_ops::*;
pub use git_ops::*;
pub use app::*;
pub use extension_ops::*;
pub use monitoring::*;
pub use terminal_ops::*;
pub use window_ops::*;
pub use debug_ops::*;
pub use search_ops::*;
pub use session_ops::*;
pub use command_registry::*;
pub use command_ops::*;
pub use menu_registry::*;
pub use menu_ops::*;
pub use extension_menu_parser::*;
pub use keybinding_registry::*;
pub use keybinding_ops::*;
pub use extension_keybinding_parser::*;
pub use status_bar_registry::*;
pub use status_bar_ops::*;
pub use activity_bar_registry::*;
pub use activity_bar_ops::*;
pub use language_features_registry::*;
pub use language_features_ops::*;
pub use workspace_registry::*;
pub use workspace_ops::*;
pub use filesystem_registry::*;
pub use filesystem_ops::*;
pub use textdocument_registry::*;
pub use textdocument_ops::*;
pub use configuration_registry::*;
pub use configuration_ops::*;
pub use debug_configuration_registry::*;
pub use debug_configuration_ops::*;
pub use theme_registry::*;
pub use theme_ops::*;
pub use task_registry::*;
pub use task_ops::*;
pub use settings_ui_registry::*;
pub use settings_ui_ops::*;
pub use marketplace_ui_registry::*;
pub use marketplace_ui_ops::*;
pub use test_runner_registry::*;
pub use test_runner_ops::*;
pub use secrets_ops::*;
