//! Node.js binary integrity verification.
//!
//! On startup, the extension host verifies the SHA256 hash of the resolved
//! Node.js binary against known-good hashes. If the hash doesn't match, the
//! extension host refuses to start.
//!
//! Hashes are read from the `allowed-hashes.json` file bundled next to the
//! Node.js binary. The download script (`scripts/download-node.sh`) generates
//! this file automatically.
//!
//! For development, set `DSCODE_SKIP_NODE_VERIFY=1` to bypass verification.

use sha2::{Digest, Sha256};
use std::fs;
use std::path::{Path, PathBuf};
use tracing::{info, warn};

/// Name of the hash list file generated by the download script.
const HASHES_FILE: &str = "allowed-hashes.json";

/// Locate the allowed-hashes.json file relative to the binary.
///
/// Looks in the same directory as the Node.js binary, then falls back to
/// the resource directory embedded in the Tauri bundle.
fn find_hashes_file(binary_path: &Path) -> Option<PathBuf> {
    // Look next to the Node.js binary first
    if let Some(parent) = binary_path.parent() {
        let candidate = parent.join(HASHES_FILE);
        if candidate.exists() {
            return Some(candidate);
        }
    }

    // Fall back: look relative to the current executable
    if let Ok(exe_path) = std::env::current_exe() {
        let mut dir = exe_path.parent().map(Path::to_path_buf);
        for _ in 0..4 {
            if let Some(d) = &dir {
                let candidate = d.join(HASHES_FILE);
                if candidate.exists() {
                    return Some(candidate);
                }
                dir = d.parent().map(Path::to_path_buf);
            }
        }
    }

    None
}

/// Load allowed hashes from the JSON file.
fn load_allowed_hashes(hashes_path: &Path) -> Result<Vec<String>, String> {
    let data = fs::read_to_string(hashes_path)
        .map_err(|e| format!("Failed to read hashes file {:?}: {}", hashes_path, e))?;

    let hashes: Vec<String> = serde_json::from_str(&data)
        .map_err(|e| format!("Invalid hashes file {:?}: {}", hashes_path, e))?;

    if hashes.is_empty() {
        return Err(format!(
            "Hashes file {:?} contains no entries",
            hashes_path
        ));
    }

    Ok(hashes)
}

/// Verify the SHA256 hash of a binary file against allowed hashes.
///
/// Returns `Ok(())` if the hash matches, or `Err` with a description of the
/// mismatch. If the `DSCODE_SKIP_NODE_VERIFY` environment variable is set,
/// verification is skipped.
pub fn verify_binary(binary_path: &Path) -> Result<(), String> {
    // Allow bypass for development / CI
    if std::env::var("DSCODE_SKIP_NODE_VERIFY").is_ok() {
        warn!("Node.js binary verification skipped (DSCODE_SKIP_NODE_VERIFY set)");
        return Ok(());
    }

    let hashes_file = match find_hashes_file(binary_path) {
        Some(path) => path,
        None => {
            #[cfg(debug_assertions)]
            {
                warn!(
                    "allowed-hashes.json not found near {:?} — skipping binary verification (debug mode)",
                    binary_path
                );
                return Ok(());
            }
            #[cfg(not(debug_assertions))]
            {
                return Err(format!(
                    "allowed-hashes.json not found near {:?}. Run scripts/download-node.sh to download Node.js and generate the hash file.",
                    binary_path
                ));
            }
        }
    };

    let allowed_hashes = load_allowed_hashes(&hashes_file)?;

    let hash = compute_file_hash(binary_path)?;

    if allowed_hashes.contains(&hash) {
        info!("Node.js binary hash verified successfully");
        Ok(())
    } else {
        Err(format!(
            "Node.js binary hash mismatch: {} (expected one of: {:?})",
            hash, allowed_hashes
        ))
    }
}

/// Compute the SHA256 hash of a file.
fn compute_file_hash(path: &Path) -> Result<String, String> {
    let data =
        fs::read(path).map_err(|e| format!("Failed to read binary {:?}: {}", path, e))?;

    let mut hasher = Sha256::new();
    hasher.update(&data);
    let result = hasher.finalize();

    Ok(format!("{:x}", result))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    #[test]
    fn test_compute_file_hash() {
        let dir = tempfile::tempdir().unwrap();
        let file_path = dir.path().join("test_binary");
        let mut file = fs::File::create(&file_path).unwrap();
        file.write_all(b"test content").unwrap();
        drop(file);

        let hash = compute_file_hash(&file_path).unwrap();
        assert_eq!(hash.len(), 64);
        assert!(!hash.is_empty());
    }

    #[test]
    fn test_verify_binary_skips_with_env() {
        std::env::set_var("DSCODE_SKIP_NODE_VERIFY", "1");
        let result = verify_binary(Path::new("/nonexistent"));
        std::env::remove_var("DSCODE_SKIP_NODE_VERIFY");
        assert!(result.is_ok());
    }

    #[test]
    fn test_verify_binary_fails_without_hashes_file_in_release() {
        // In debug mode, missing hashes file is OK.
        // In release mode, it would fail. This test just validates
        // the function doesn't panic.
        let result = verify_binary(Path::new("/tmp/nonexistent-node"));
        // In debug mode this should pass (warn and skip), in release it fails
        #[cfg(debug_assertions)]
        assert!(result.is_ok());
        #[cfg(not(debug_assertions))]
        assert!(result.is_err());
    }

    #[test]
    fn test_load_allowed_hashes_valid() {
        let dir = tempfile::tempdir().unwrap();
        let file_path = dir.path().join(HASHES_FILE);
        let hashes: Vec<&str> = vec![
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
            "a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a",
        ];
        fs::write(&file_path, serde_json::to_string(&hashes).unwrap()).unwrap();

        let loaded = load_allowed_hashes(&file_path).unwrap();
        assert_eq!(loaded.len(), 2);
    }

    #[test]
    fn test_load_allowed_hashes_empty() {
        let dir = tempfile::tempdir().unwrap();
        let file_path = dir.path().join(HASHES_FILE);
        let hashes: Vec<&str> = vec![];
        fs::write(&file_path, serde_json::to_string(&hashes).unwrap()).unwrap();

        let result = load_allowed_hashes(&file_path);
        assert!(result.is_err());
    }
}
